-- ============================================================
-- NetPulse NOC Database
-- Migration: 001_initial_schema
-- Purpose : Create the initial relational schema
-- Target  : Oracle Database Free
-- ============================================================

-- IMPORTANT:
-- This migration is destructive if executed against an existing
-- schema containing objects with the same names.
-- Only run this migration on a new/empty development schema.

-- ============================================================
-- 1. AppUsers
-- ============================================================

CREATE TABLE AppUsers (
    UserId NUMBER GENERATED BY DEFAULT AS IDENTITY,
    Username VARCHAR2(50) NOT NULL,
    Password VARCHAR2(255) NOT NULL,
    FirstName VARCHAR2(50),
    LastName VARCHAR2(50),
    FullName VARCHAR2(100),
    Role VARCHAR2(30),

    CONSTRAINT pk_appusers
        PRIMARY KEY (UserId),

    CONSTRAINT uq_appusers_username
        UNIQUE (Username)
);

-- ============================================================
-- 2. Devices
-- ============================================================

CREATE TABLE Devices (
    DeviceId NUMBER GENERATED BY DEFAULT AS IDENTITY,
    Name VARCHAR2(63) NOT NULL,
    Type VARCHAR2(50),
    IP VARCHAR2(45) NOT NULL,
    Status VARCHAR2(20),
    Role VARCHAR2(30),

    CONSTRAINT pk_devices
        PRIMARY KEY (DeviceId),

    CONSTRAINT uq_devices_name
        UNIQUE (Name),

    CONSTRAINT uq_devices_ip
        UNIQUE (IP)
);

-- ============================================================
-- 3. AlertRules
-- ============================================================

CREATE TABLE AlertRules (
    RuleId NUMBER GENERATED BY DEFAULT AS IDENTITY,
    Name VARCHAR2(100) NOT NULL,
    Role VARCHAR2(30),
    EntityType VARCHAR2(50),
    Status VARCHAR2(20),

    CONSTRAINT pk_alertrules
        PRIMARY KEY (RuleId)
);

-- ============================================================
-- 4. TelemetryEvents
-- ============================================================

CREATE TABLE TelemetryEvents (
    EventId NUMBER GENERATED BY DEFAULT AS IDENTITY,
    DeviceId NUMBER NOT NULL,
    EventType VARCHAR2(50),
    Payload VARCHAR2(4000),
    Severity VARCHAR2(20),

    CONSTRAINT pk_telemetryevents
        PRIMARY KEY (EventId),

    CONSTRAINT fk_telemetryevents_device
        FOREIGN KEY (DeviceId)
        REFERENCES Devices(DeviceId)
);

-- ============================================================
-- 5. Alerts
-- ============================================================

CREATE TABLE Alerts (
    AlertId NUMBER GENERATED BY DEFAULT AS IDENTITY,
    RuleId NUMBER,
    EventId NUMBER,
    Message VARCHAR2(500),
    Status VARCHAR2(20),

    CONSTRAINT pk_alerts
        PRIMARY KEY (AlertId),

    CONSTRAINT fk_alerts_rule
        FOREIGN KEY (RuleId)
        REFERENCES AlertRules(RuleId),

    CONSTRAINT fk_alerts_event
        FOREIGN KEY (EventId)
        REFERENCES TelemetryEvents(EventId)
);

-- ============================================================
-- 6. Incidents
-- ============================================================

CREATE TABLE Incidents (
    IncidentId NUMBER GENERATED BY DEFAULT AS IDENTITY,
    AlertId NUMBER NOT NULL,
    AssignedTo NUMBER,
    Status VARCHAR2(20),

    CONSTRAINT pk_incidents
        PRIMARY KEY (IncidentId),

    CONSTRAINT fk_incidents_alert
        FOREIGN KEY (AlertId)
        REFERENCES Alerts(AlertId),

    CONSTRAINT fk_incidents_user
        FOREIGN KEY (AssignedTo)
        REFERENCES AppUsers(UserId)
);

-- ============================================================
-- 7. Audits
-- ============================================================

CREATE TABLE Audits (
    AuditId NUMBER GENERATED BY DEFAULT AS IDENTITY,
    UserId NUMBER NOT NULL,
    Action VARCHAR2(100),
    EntityType VARCHAR2(50),

    CONSTRAINT pk_audits
        PRIMARY KEY (AuditId),

    CONSTRAINT fk_audits_user
        FOREIGN KEY (UserId)
        REFERENCES AppUsers(UserId)
);

COMMIT;

-- ============================================================
-- Migration completed
-- ============================================================